name: Update GetText

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install mdpo dependency
      run: sudo apt-get install libmd4c-dev libmd4c-html0 libmd4c-html0-dev
    - name: install mdpo
      run: pip install mdpo
    - name: run update-po.py
      run: python ./scripts/update-po.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "locales: Automated Gettext Update(Manually Triggered)"
        committer: GitHub <noreply@github.com> 
        signoff: true
        author: GitHub <noreply@github.com> 
